# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2.1
language: objective-c
sudo: required

branches:
 only:
 - master
# cache: cocoapods
# podfile: Example/Podfile
before_install:
 - brew update
 - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
 - export LANG=en_US.UTF-8
 - gem install xcpretty --no-ri --no-rdoc
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example
script:
- xcodebuild -workspace Example/ResizableView.xcworkspace -scheme ResizableView-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' clean build test | xcpretty --test --color

- pod lib lint --quick
